version: '2'

services:
  postgres:
    image: 'postgres:10.3-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRESS_PASSWOD=example
      - POSTGRES_USER=store
      - POSTGRES_DB=store_production
  app:
    image: 'store:1.0'
    ports:
      - "4000:3000"
    environment:
      - DB_HOST=postgres
      - STORE_DATABASE_PASSWORD=example
      - RAILS_ENV=production

volumes:
  postgres:
    
